from flask import Flask, render_template, request, session, redirect, url_for, jsonify
import google.generativeai as genai
import json
import os
import re
from dotenv import load_dotenv
import database

# Load .env file
load_dotenv()

app = Flask(__name__)
app.secret_key = os.environ.get("SECRET_KEY", "kadoz-secret-2026")

# Initialize database
database.init_db()

# ── Gemini API ────────────────────────────────────────────────────────────────
GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY")

# ── Translations ──────────────────────────────────────────────────────────────
TRANSLATIONS = {
    "fr": {
        "dir": "ltr",
        "lang_label": "Langue",
        "tagline": "Idées cadeaux propulsées par Gemini AI",
        "page_title": "Trouvez le cadeau parfait",
        "page_subtitle": "Décrivez la personne, on s'occupe du reste 🎁",
        "label_age": "Âge de la personne",
        "label_gender": "Sexe",
        "gender_man": "Homme",
        "gender_woman": "Femme",
        "label_budget": "Budget",
        "label_interets": "Centres d'intérêt",
        "label_suggestions": "Idées populaires",
        "placeholder_age": "Ex : 28",
        "placeholder_budget": "Ex : 80",
        "placeholder_interets": "Ex : musique, voyage, cuisine…",
        "btn_generate": "Générer mes 5 cadeaux parfaits",
        "error_age": "Veuillez entrer un âge valide (1–120).",
        "error_gender": "Veuillez choisir le sexe.",
        "error_currency": "Veuillez choisir une devise.",
        "error_budget": "Veuillez entrer un budget valide (> 0).",
        "error_interets": "Merci de préciser au moins un intérêt.",
        "results_badge": "Générés par Gemini AI",
        "results_title": "5 Cadeaux Parfaits",
        "results_for": "Pour",
        "results_age_unit": "ans",
        "results_who_likes": "qui aime",
        "results_budget": "Budget",
        "btn_back": "Nouvelle recherche",
        "btn_retry": "Régénérer les suggestions",
        "retry_text": "Vous n'êtes pas satisfait ? Générez de nouvelles suggestions !",
        "estimated": "estimé",
        "footer": "Propulsé par Gemini AI",
        "dark_mode": "Mode sombre",
        "light_mode": "Mode clair",
        "tags": [
            ("musique","🎵 Musique"),("voyage","✈️ Voyage"),("cuisine","🍳 Cuisine"),
            ("sport","🏋️ Sport"),("lecture","📚 Lecture"),("gaming","🎮 Gaming"),
            ("photographie","📷 Photo"),("jardinage","🌱 Jardinage"),("mode","👗 Mode"),
            ("art","🎨 Art"),("yoga","🧘 Yoga"),("technologie","💻 Tech"),
            ("nature","🌿 Nature"),("cinema","🎬 Cinéma"),("bien-etre","✨ Bien-être"),
        ],
        "gemini_prompt": lambda age, gender, interests, budget, currency: f"""Tu es un expert en shopping. La personne est un(e) {gender} de {age} ans, elle aime {interests}. 
Le budget est de {budget} {currency}.
Propose exactement 5 cadeaux créatifs et originaux adaptés à son profil.
Réponds UNIQUEMENT en JSON valide, un array de 5 objets avec:
{{"nom": "...", "emoji": "...", "raison": "...(max 2 phrases)", "lien_logique": "Lien avec ses intérêts...", "prix_min": 10, "prix_max": 50, "categorie": "Technologie|Bien-être|Culture|Sport|Créativité|Voyage|Gastronomie|Mode", "image_query": "2 specific English nouns separated by commas, e.g. 'gaming,mouse' or 'leather,wallet'"}}
Le prix MIN et MAX doivent être dans la devise {currency}. Tous les prix doivent être compatibles avec le budget total de {budget} {currency}.
Réponds UNIQUEMENT avec le JSON."""
    },
    "en": {
        "dir": "ltr",
        "lang_label": "Language",
        "tagline": "Gift ideas powered by Gemini AI",
        "page_title": "Find the perfect gift",
        "page_subtitle": "Describe the person, we handle the rest 🎁",
        "label_age": "Person's age",
        "label_gender": "Gender",
        "gender_man": "Man",
        "gender_woman": "Woman",
        "label_budget": "Budget",
        "label_interets": "Interests",
        "label_suggestions": "Popular ideas",
        "placeholder_age": "E.g.: 28",
        "placeholder_budget": "E.g.: 80",
        "placeholder_interets": "E.g.: music, travel, cooking…",
        "btn_generate": "Generate my 5 perfect gifts",
        "error_age": "Please enter a valid age (1–120).",
        "error_gender": "Please choose a gender.",
        "error_currency": "Please choose a currency.",
        "error_budget": "Please enter a valid budget (> 0).",
        "error_interets": "Please specify at least one interest.",
        "results_badge": "Generated by Gemini AI",
        "results_title": "5 Perfect Gifts",
        "results_for": "For a",
        "results_age_unit": "year-old",
        "results_who_likes": "who likes",
        "results_budget": "Budget",
        "btn_back": "New search",
        "btn_retry": "Regenerate suggestions",
        "retry_text": "Not satisfied? Generate new suggestions!",
        "estimated": "estimated",
        "footer": "Powered by Gemini AI",
        "dark_mode": "Dark mode",
        "light_mode": "Light mode",
        "tags": [
            ("music","🎵 Music"),("travel","✈️ Travel"),("cooking","🍳 Cooking"),
            ("sport","🏋️ Sport"),("reading","📚 Reading"),("gaming","🎮 Gaming"),
            ("photography","📷 Photo"),("gardening","🌱 Gardening"),("fashion","👗 Fashion"),
            ("art","🎨 Art"),("yoga","🧘 Yoga"),("technology","💻 Tech"),
            ("nature","🌿 Nature"),("cinema","🎬 Cinema"),("wellness","✨ Wellness"),
        ],
        "gemini_prompt": lambda age, gender, interests, budget, currency: f"""You are a shopping expert. The person is a {gender}, {age} years old and likes {interests}.
The budget is {budget} {currency}.
Suggest exactly 5 creative and original gifts tailored to their profile.
Reply ONLY in valid JSON, an array of 5 objects with:
{{"nom": "...", "emoji": "...", "raison": "...(max 2 sentences)", "lien_logique": "Link to their interests...", "prix_min": 10, "prix_max": 50, "categorie": "Technology|Wellness|Culture|Sport|Creativity|Travel|Food|Fashion", "image_query": "2 specific English nouns separated by commas, e.g. 'gaming,mouse' or 'leather,wallet'"}}
Min and Max prices must be in {currency}. All prices must be compatible with a total budget of {budget} {currency}.
Reply ONLY with the JSON."""
    },
    "ar": {
        "dir": "rtl",
        "lang_label": "اللغة",
        "tagline": "أفكار هدايا مدعومة بـ Gemini AI",
        "page_title": "اعثر على الهدية المثالية",
        "page_subtitle": "صف الشخص، ونحن نتولى الباقي 🎁",
        "label_age": "عمر الشخص",
        "label_gender": "الجنس",
        "gender_man": "ذكر",
        "gender_woman": "أنثى",
        "label_budget": "الميزانية",
        "label_interets": "الاهتمامات",
        "label_suggestions": "أفكار شائعة",
        "placeholder_age": "مثال: 28",
        "placeholder_budget": "مثال: 80",
        "placeholder_interets": "مثال: موسيقى، سفر، طبخ…",
        "btn_generate": "توليد 5 هدايا مثالية",
        "error_age": "يرجى إدخال عمر صحيح (1–120).",
        "error_gender": "يرجى اختيار الجنس.",
        "error_currency": "يرجى اختيار عملة.",
        "error_budget": "يرجى إدخال ميزانية صحيحة (> 0).",
        "error_interets": "يرجى تحديد اهتمام واحد على الأقل.",
        "results_badge": "تم توليدها بواسطة Gemini AI",
        "results_title": "5 هدايا مثالية",
        "results_for": "لـ",
        "results_age_unit": "سنة",
        "results_who_likes": "يحب",
        "results_budget": "الميزانية",
        "btn_back": "بحث جديد",
        "btn_retry": "إعادة توليد الاقتراحات",
        "retry_text": "غير راضٍ؟ ولّد اقتراحات جديدة!",
        "estimated": "تقدير",
        "footer": "مدعوم بواسطة Gemini AI",
        "dark_mode": "الوضع الداكن",
        "light_mode": "الوضع الفاتح",
        "tags": [
            ("موسيقى","🎵 موسيقى"),("سفر","✈️ سفر"),("طبخ","🍳 طبخ"),
            ("رياضة","🏋️ رياضة"),("قراءة","📚 قراءة"),("ألعاب","🎮 ألعاب"),
            ("تصوير","📷 تصوير"),("بستنة","🌱 بستنة"),("موضة","👗 موضة"),
            ("فن","🎨 فن"),("يوغا","🧘 يوغا"),("تكنولوجيا","💻 تقنية"),
            ("طبيعة","🌿 طبيعة"),("سينما","🎬 سينما"),("عافية","✨ عافية"),
        ],
        "gemini_prompt": lambda age, gender, interests, budget, currency: f"""أنت خبير في التسوق. الشخص {gender} وعمره {age} سنة ويحب {interests}.
الميزانية هي {budget} {currency}.
اقترح بالضبط 5 هدايا مبدعة وأصلية مصممة لملفهم الشخصي.
أجب فقط بـ JSON صحيح، مصفوفة من 5 كائنات بـ:
{{"nom": "...", "emoji": "...", "raison": "...(جملتان كحد أقصى)", "lien_logique": "الصلة باهتماماتهم...", "prix_min": 10, "prix_max": 50, "categorie": "تكنولوجيا|صحة|ثقافة|رياضة|إبداع|سفر|طعام|موضة", "image_query": "2 specific English nouns separated by commas, e.g. 'gaming,mouse' or 'leather,wallet'"}}
يجب أن تكون الأسعار الدنيا والقصوى بعملة {currency}.
يجب أن تكون جميع الأسعار متوافقة مع ميزانية إجمالية قدرها {budget} {currency}.
أجب فقط بـ JSON."""
    }
}

CARD_COLORS = ["purple", "blue", "green", "amber", "pink"]


def get_lang():
    return session.get("lang", "fr")


def get_theme():
    return session.get("theme", "dark")


def is_logged_in():
    return "user_id" in session


def generate_gifts(age, gender, interests, budget, lang, currency="EUR", api_key_override=None):
    key = api_key_override or os.environ.get("GEMINI_API_KEY")
    if not key:
        return None, "Clé API Gemini manquante."
    
    genai.configure(api_key=key)
    # Using 'gemini-flash-latest' to match the 2026 futuristic environment
    model = genai.GenerativeModel("gemini-flash-latest")
    t = TRANSLATIONS[lang]
    prompt = t["gemini_prompt"](age, gender, interests, budget, currency)

    try:
        response = model.generate_content(prompt)
        raw = response.text.strip()
        raw = re.sub(r"^```(?:json)?\n?", "", raw)
        raw = re.sub(r"\n?```$", "", raw)
        gifts = json.loads(raw)
        for i, gift in enumerate(gifts):
            gift["color"] = CARD_COLORS[i % len(CARD_COLORS)]
            query = gift.get("image_query", gift["nom"]).replace(" ", "").replace('"', '').replace("'", "")
            gift["image_url"] = f"https://loremflickr.com/600/400/{query}"
        return gifts, None
    except Exception as e:
        return None, str(e)


def base_context():
    lang = get_lang()
    return {
        "t": TRANSLATIONS[lang],
        "lang": lang,
        "theme": get_theme(),
        "langs": [("fr", "🇫🇷 FR"), ("en", "🇬🇧 EN"), ("ar", "🇸🇦 AR")],
        "has_key": bool(session.get("api_key") or os.environ.get("GEMINI_API_KEY")),
        "user_id": session.get("user_id"),
        "user_name": session.get("user_name"),
        "is_logged_in": is_logged_in()
    }


# ── Routes ────────────────────────────────────────────────────────────────────

@app.route("/set-api-key", methods=["POST"])
def set_api_key():
    key = request.form.get("api_key", "").strip()
    if key:
        session["api_key"] = key
    return redirect(request.referrer or url_for("index"))


@app.route("/set-lang/<lang>")
def set_lang(lang):
    if lang in TRANSLATIONS:
        session["lang"] = lang
    return redirect(request.referrer or url_for("index"))


@app.route("/set-theme/<theme>")
def set_theme(theme):
    if theme in ("dark", "light"):
        session["theme"] = theme
    return redirect(request.referrer or url_for("index"))


@app.route("/", methods=["GET"])
def index():
    ctx = base_context()
    # Read from session for state persistence
    return render_template("index.html", errors={}, api_error=None,
                           old_age=session.get("age", ""), 
                           old_gender=session.get("gender", ""), 
                           old_interets=session.get("interets", ""), 
                           old_budget=session.get("budget", ""), 
                           old_currency=session.get("currency", "EUR"), **ctx)


# ── Auth Routes ───────────────────────────────────────────────────────────────

@app.route("/login", methods=["GET", "POST"])
def login():
    if request.method == "POST":
        username = request.form.get("username", "").strip().lower()
        password = request.form.get("password", "").strip()
        user = database.login_user(username, password)
        if user:
            session["user_id"] = user["id"]
            session["user_name"] = user["username"]
            return redirect(url_for("index"))
        return render_template("auth.html", error="Identifiants invalides", mode="login", **base_context())
    return render_template("auth.html", mode="login", **base_context())


@app.route("/register", methods=["GET", "POST"])
def register():
    if request.method == "POST":
        username = request.form.get("username", "").strip().lower()
        password = request.form.get("password", "").strip()
        if not username or not password:
            return render_template("auth.html", error="Veuillez remplir tous les champs", mode="register", **base_context())
        if database.register_user(username, password):
            return redirect(url_for("login"))
        return render_template("auth.html", error="Nom d'utilisateur déjà pris", mode="register", **base_context())
    return render_template("auth.html", mode="register", **base_context())


@app.route("/logout")
def logout():
    session.pop("user_id", None)
    session.pop("user_name", None)
    return redirect(url_for("login"))


# ── Favorites ────────────────────────────────────────────────────────────────

@app.route("/toggle-favorite", methods=["POST"])
def toggle_favorite():
    if not is_logged_in():
        return jsonify({"success": False, "error": "Veuillez vous connecter"}), 401
    
    gift_name = request.json.get("gift_name")
    gift_data = request.json.get("gift_data")
    
    user_id = session["user_id"]
    if database.is_favorite(user_id, gift_name):
        database.remove_favorite(user_id, gift_name)
        return jsonify({"success": True, "action": "removed"})
    else:
        database.add_favorite(user_id, gift_name, json.dumps(gift_data))
        return jsonify({"success": True, "action": "added"})


@app.route("/favorites")
def favorites():
    if not is_logged_in():
        return redirect(url_for("login"))
    
    ctx = base_context()
    gifts = database.get_favorites(session["user_id"])
    return render_template("favorites.html", gifts=gifts, **ctx)


@app.route("/generate", methods=["POST", "GET"])
def generate():
    lang = get_lang()
    t = TRANSLATIONS[lang]
    ctx = base_context()

    if request.method == "POST":
        age = request.form.get("age", "").strip()
        gender = request.form.get("gender", "").strip()
        interets = request.form.get("interets", "").strip()
        budget = request.form.get("budget", "").strip()
        currency = request.form.get("currency", "").strip()

        # Update session for persistence
        session["age"] = age
        session["gender"] = gender
        session["interets"] = interets
        session["budget"] = budget
        session["currency"] = currency

        errors = {}
        if not age or not age.isdigit() or not (1 <= int(age) <= 120):
            errors["age"] = t["error_age"]
        if not gender or gender not in ["homme", "femme"]:
            errors["gender"] = t["error_gender"]
        if not budget or not budget.replace(".", "").isdigit() or float(budget) <= 0:
            errors["budget"] = t["error_budget"]
        if not currency or currency not in ["DH", "EUR", "USD"]:
            errors["currency"] = t["error_currency"]
        if not interets:
            errors["interets"] = t["error_interets"]

        if errors:
            return render_template("index.html", errors=errors, api_error=None,
                                   old_age=age, old_gender=gender, old_interets=interets, 
                                   old_budget=budget, old_currency=currency, **ctx)

        gender_label = t["gender_man"] if gender == "homme" else t["gender_woman"]
        gifts, error = generate_gifts(int(age), gender_label, interets, float(budget), lang, 
                                      currency=currency, api_key_override=session.get("api_key"))

        if error:
            return render_template("index.html", api_error=error, errors={},
                                   old_age=age, old_gender=gender, old_interets=interets, 
                                   old_budget=budget, old_currency=currency, **ctx)

        session["gifts"] = gifts
    else:
        # GET request: load from session (useful after theme/lang change)
        age = session.get("age")
        gender = session.get("gender")
        interets = session.get("interets")
        budget = session.get("budget")
        currency = session.get("currency")
        gifts = session.get("gifts")

        if not gifts:
            return redirect(url_for("index"))

    if is_logged_in():
        user_id = session["user_id"]
        for gift in gifts:
            gift["is_favorite"] = database.is_favorite(user_id, gift["nom"])

    return render_template("results.html", gifts=gifts,
                           age=age, gender=gender, interets=interets, 
                           budget=budget, currency=currency, **ctx)


if __name__ == "__main__":
    app.run(debug=False, host='0.0.0.0', port=3000)
